#! /bin/sh

CURL=/usr/bin/curl
DATE=/usr/bin/date

# Site internet à controler
URL='http://192.168.0.220/wp-json/wp/v2/comments?after'
#URL='http://128.1.1.220/wp-json/wp/v2/comments?after'

# Seuil d'alerte "WARNING" du nombre de message
WARNING=4
# Seuil d'alerte "CRITIQUE" du nombre de message
SPAM=10

#################Création de la date - 4 heures#####################

datedutest=$(date --date="4 hours ago" --iso-8601=seconds | cut -c1-19)

#################Comptage du nombre de commentaire###################
# Première méthode
#EXTRACT=$(curl -X GET $URL=$datedutest | grep -wo "date_gmt" | wc -l)
# Deuxième méthode
EXTRACT=$(curl -X GET $URL=$datedutest | jq '. | length')

#################Test de sortie de la sonde##########################

if [ $EXTRACT -ge $SPAM  ]
then
	echo "CRITIQUE - Attention SPAM en cours ! (Nombre de message sur les 4 dernières heures: $EXTRACT)"
	exit 2
elif [ $EXTRACT -ge $WARNING ]
then
	echo "WARNING - Attention suspicion de SPAM (Nombre de message sur les 4 dernières heures: $EXTRACT)"
	exit 1
elif [ $EXTRACT -lt $WARNING ]
then
	echo "OK - Pas de SPAM (Nombre de message sur les 4 dernières heures: $EXTRACT)"
	exit 0
else
	echo "UNKNOW - Problème sur la sonde"
	exit 3
fi
